# Generated by Django 3.0.6 on 2022-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
