# Generated by Django 3.0.6 on 2022-03-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20220310_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='type',
        ),
    ]
